Feature/ch122268/piewidget
CartoDB/carto-react-lib pull request #36
Opened 2020-11-30 18:02 UTC by builtbyedgar

2021-01-22 10:52 UTC, albertoarana requested changes

2021-01-22 10:52 UTC, albertoarana commented on src/ui/utils/getChartSerie.js
> +export default function getChartSerie (chart, index) {
This function can be in `chartUtils`

2021-01-22 12:01 UTC, albertoarana approved these changes

2021-02-11 12:25 UTC, VictorVelarde requested changes
Nice work, but 3 aspects to review before merging:
1. order legend items desc by % ?
2. default colors
3. possible bug on hover?

See internal discussion at slack

2021-03-01 16:18 UTC, VictorVelarde commented
There is a derived issue on histogram and its setColor not working fine, when trying to filter. I'm currently checking it.

2021-03-01 18:38 UTC, VictorVelarde approved these changes
👍🏻

2021-03-01 18:40 UTC, merged

2021-03-01 18:42 UTC, VictorVelarde commented
Finally merged 🚀  after polishing some details / (cc @borja-munoz)